#!/usr/bin/env node
// Data + engine verification. Runs against docs/ (build first).
// Exits non-zero on any problem, so it works as a pre-commit / CI gate.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "docs/index.html"), "utf8");
const js = html.slice(html.indexOf("<script>") + 8, html.lastIndexOf("</script>"));

// Evaluate the shipped bundle in a bare sandbox: no DOM, so stop before app.js.
const upto = js.indexOf("/* ================= state ================= */");
const bundle = js.slice(0, upto);
const ctx = {};
new Function("ctx", bundle + "\nObject.assign(ctx,{LINES,KIND,SRC,PZ,ECO,START,startPos,fenPos,findMove,make,san,perft,legal,uciOf,sq,ix,matVerdict,refuteLeaks,EVL,EVL_PROBE,DEEP,cmpScore,gradeMove,posKey,CHO,CHO_BANDS,CHO_FLOOR,FRQ_BANDS,EVL_TPROBE,inCheck,gradeRow,GRADE});")(ctx);
const { LINES, KIND, SRC, PZ, ECO, START, startPos, fenPos, findMove, make, san, perft, legal, matVerdict, refuteLeaks, EVL, EVL_PROBE, DEEP, cmpScore, gradeMove, posKey, CHO, CHO_BANDS, CHO_FLOOR, FRQ_BANDS, EVL_TPROBE, inCheck, gradeRow, GRADE } = ctx;
const keyOf = posKey;

let fail = 0;
const bad = (m) => { console.error("  ✗ " + m); fail++; };

// 1. move generator against the standard perft positions
const PERFT = [
  ["start", null, [20, 400, 8902, 197281]],
  ["kiwipete", "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq -", [48, 2039, 97862]],
  ["position 3", "8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - -", [14, 191, 2812, 43238]],
  ["position 4", "r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq -", [6, 264, 9467]],
];
for (const [name, fen, expected] of PERFT) {
  const p = fen ? fenPos(fen) : startPos();
  expected.forEach((want, i) => {
    const got = perft(p, i + 1);
    if (got !== want) bad(`perft ${name} depth ${i + 1}: ${got}, expected ${want}`);
  });
}
console.log(`✓ move generator matches perft on ${PERFT.length} positions`);

// 2. every line replays legally and its notation is what the generator produces
const TAGS = new Set(["game", "book", "eco", "theory", "model", "synthetic"]);
const ids = new Set(LINES.map((l) => l.id));
for (const k of Object.keys(KIND)) if (!ids.has(k)) bad(`KIND tags unknown line "${k}"`);
for (const k of Object.keys(SRC)) if (!ids.has(k)) bad(`SRC has a source for unknown line "${k}"`);
let moves = 0;
const kinds = {};
for (const l of LINES) {
  const tag = KIND[l.id];
  kinds[tag || "untagged"] = (kinds[tag || "untagged"] || 0) + 1;
  if (!tag) bad(`${l.id} has no provenance tag`);
  else if (!TAGS.has(tag)) bad(`${l.id} has an unrecognised tag "${tag}"`);
  if (tag === "game" && !SRC[l.id]) bad(`${l.id} is tagged game but has no entry in SRC`);
  let p = l.start === START ? startPos() : fenPos(l.start);
  const seenNotes = new Map();
  l.moves.forEach((mv, i) => {
    const m = findMove(p, mv[0]);
    if (!m) return bad(`${l.id} move ${i + 1} (${mv[1]}) is not legal`);
    const produced = san(p, m).replace(/[+#]/g, "");
    if (produced !== mv[1].replace(/[+#!?]/g, ""))
      bad(`${l.id} move ${i + 1} is labelled ${mv[1]}, generator says ${produced}`);
    if (mv[2]) {
      if (seenNotes.has(mv[2]))
        bad(`${l.id}: the note "${mv[2]}" is on both ply ${seenNotes.get(mv[2])} and ply ${i + 1}`);
      else seenNotes.set(mv[2], i + 1);
    }
    moves++;
    p = make(p, m);
  });
}
console.log(`✓ ${LINES.length} lines, ${moves} moves, all legal with matching notation`);
console.log(`  tags: ${Object.entries(kinds).map(([k, v]) => `${k} ${v}`).join(", ")}`);

// 3. ECO stays in sync with the lines it names (eco.js is generated by
// tools/build-eco.mjs from the same LINES data, so it can drift if lines.js
// changes without a rebuild)
const lineLen = new Map(LINES.map((l) => [l.id, l.moves.length]));
for (const [id, entries] of Object.entries(ECO)) {
  if (!lineLen.has(id)) { bad(`ECO has entries for unknown line "${id}"`); continue; }
  for (const [ply] of entries)
    if (ply > lineLen.get(id)) bad(`ECO ${id}: ply ${ply} is beyond its ${lineLen.get(id)} moves`);
}
console.log(`✓ ${Object.keys(ECO).length} ECO entries reference real lines and in-range plies`);

// 4. every puzzle replays from its FEN with matching display SAN
let pz = 0;
for (const z of PZ) {
  let p;
  try { p = fenPos(z.f); } catch { bad(`puzzle ${z.id}: unreadable FEN`); continue; }
  let ok = true;
  for (let i = 0; i < z.m.length; i++) {
    const m = findMove(p, z.m[i]);
    if (!m) { bad(`puzzle ${z.id}: ${z.m[i]} is not legal`); ok = false; break; }
    const produced = san(p, m).replace(/[+#]/g, "");
    const stored = (z.s[i] || "").replace(/[+#!?]/g, "");
    if (produced !== stored) { bad(`puzzle ${z.id} move ${i + 1} is labelled ${z.s[i]}, generator says ${produced}`); ok = false; }
    p = make(p, m);
  }
  if (ok) pz++;
}
console.log(`✓ ${pz}/${PZ.length} puzzles replay legally with matching display notation`);

// 5. the material search behind "refute the wrong move": hand-set positions where
// the refutation is unambiguous. matVerdict(pos, m) compares best-play material
// before a move against best play after it; these pin the reply it names and the
// swing it reports, so a regression in the search fails loudly here rather than
// shipping a wrong claim to the user.
{
  const cases = [
    // Black rook walks onto the d1 queen's back rank: hangs outright, nothing comes back
    ["hanging rook", "r3k3/8/8/8/8/8/8/3Q2K1 b - -", "a8a1", "Qxa1", 5],
    // a quiet pawn move ignores the b5 knight's fork on c7: king and rook, rook falls
    ["knight fork", "r3k3/7p/8/1N6/8/8/8/6K1 b - -", "h7h6", "Nc7+", 5],
  ];
  for (const [label, fen, uci, wantSan, wantSwing] of cases) {
    const p = fenPos(fen);
    const m = findMove(p, uci);
    if (!m) { bad(`refute ${label}: ${uci} is not legal`); continue; }
    const v = matVerdict(p, m);
    if (!v) { bad(`refute ${label}: search hit its node budget`); continue; }
    if (v.san.replace(/[+#]/g, "") !== wantSan.replace(/[+#]/g, ""))
      bad(`refute ${label}: names ${v.san}, expected ${wantSan}`);
    if (v.swing !== wantSwing)
      bad(`refute ${label}: swing ${v.swing}, expected ${wantSwing}`);
  }
  // fool's mate: the one evaluation claim the search may make is a mate it confirmed
  let fp = startPos();
  for (const u of ["f2f3", "e7e5"]) fp = make(fp, findMove(fp, u));
  const fm = matVerdict(fp, findMove(fp, "g2g4"));
  if (!fm || fm.mate !== 1 || fm.san !== "Qh4#")
    bad(`refute fool's mate: got ${JSON.stringify(fm)}, expected mate in 1 by Qh4#`);
  // a sound opening move produces no claim at all - silence is the correct output
  const quiet = matVerdict(startPos(), findMove(startPos(), "e2e4"));
  if (!quiet) bad("refute 1.e4: search hit its node budget on the start position");
  else if (quiet.swing >= 1) bad(`refute 1.e4: swing ${quiet.swing} - a sound move must stay silent`);
  // the leak guard: a refutation naming the expected move's square is suppressed,
  // and one that shares nothing with the expected move is not
  if (!refuteLeaks("Qxa1 answers it", "b1a1", "Ra1")) bad("refuteLeaks misses a destination-square leak");
  if (refuteLeaks("Nc7+ answers it", "e8g8", "O-O")) bad("refuteLeaks suppresses a clean refutation");
  console.log("✓ material search refutes the hand-set blunders and stays silent on sound moves");
}

// 6. the stored engine evaluations: every key is a parseable position, every
// stored move is legal there with the SAN this engine produces, every PV replays
// legally starting from the best move, and every score is exactly one of cp/mate.
// EVL_PROBE is the sign-convention canary: a position where the side to move is
// decisively lost, shipped with its stored negative score. Scores are
// SIDE-TO-MOVE relative; if a regeneration ever flips them White-relative, the
// probe's cp goes positive and this fails before the flip can ship.
{
  let rows = 0, pvs = 0, extra = 0, evlFail = fail;
  for (const [k, e] of Object.entries(EVL)) {
    let p;
    try { p = fenPos(k); } catch { bad(`EVL key does not parse: ${k}`); continue; }
    if (!(e.m && e.m.length) ) { bad(`EVL ${k}: no moves stored`); continue; }
    // e.x holds repertoire moves outside the ranked five, each searched on its
    // own. Same legality and score rules; it must never restate a ranked move,
    // or a grader reading both would double-count it.
    if (e.x !== undefined) {
      if (!Array.isArray(e.x) || !e.x.length) { bad(`EVL ${k}: x present but not a non-empty list`); continue; }
      const ranked = new Set(e.m.map((y) => y[0]));
      for (const y of e.x) if (ranked.has(y[0])) bad(`EVL ${k}: ${y[0]} is in both m and x`);
      extra += e.x.length;
    }
    for (const [uci, sanTxt, cp, mate] of [...e.m, ...(e.x || [])]) {
      const m = findMove(p, uci);
      if (!m) { bad(`EVL ${k}: ${uci} is not legal`); continue; }
      if (san(p, m) !== sanTxt) bad(`EVL ${k}: ${uci} labelled ${sanTxt}, generator says ${san(p, m)}`);
      if ((cp === null) === (mate === null)) bad(`EVL ${k}: ${sanTxt} must have exactly one of cp/mate, has ${cp}/${mate}`);
      rows++;
    }
    if (!(e.pv && e.pv.length)) { bad(`EVL ${k}: no pv`); continue; }
    if (e.pv[0] !== e.m[0][1]) bad(`EVL ${k}: pv starts ${e.pv[0]}, best move is ${e.m[0][1]}`);
    let q = p, ok = true;
    for (const tok of e.pv) {
      const m = ok && legal(q).find((x) => san(q, x) === tok);
      if (!m) { bad(`EVL ${k}: pv move ${tok} does not replay`); ok = false; break; }
      q = make(q, m);
    }
    if (ok) pvs++;
  }
  try { fenPos(EVL_PROBE.fen); } catch { bad("EVL_PROBE fen does not parse"); }
  if (EVL_PROBE.pov !== "stm") bad(`EVL_PROBE pov is "${EVL_PROBE.pov}", expected "stm"`);
  if ((EVL_PROBE.cp === null) === (EVL_PROBE.mate === null)) bad("EVL_PROBE must have exactly one of cp/mate");
  if (!(EVL_PROBE.cp < 0))
    bad(`EVL_PROBE cp is ${EVL_PROBE.cp}: the side to move is lost, so a side-to-move score must be negative — the sign convention has flipped`);
  if (fail === evlFail)
    console.log(`✓ ${Object.keys(EVL).length} stored evaluations: keys parse, ${rows} moves legal with matching SAN` +
      (extra ? ` (${extra} of them repertoire moves outside the ranked list)` : "") +
      `, ${pvs} PVs replay, probe sign holds`);
}

// 6a. per-candidate lines and threats (research/W5-POSITION-METADATA.md).
// p is aligned with m and xp with x: one short SAN line per stored move, each
// starting with that move and replaying legally, p[0] identical to pv. t is the
// threat: the opponent's best move from the same board with the move handed to
// them (en passant cleared), [uci, san, cp, mate, pv], scored from the
// THREATENING side's view. It must exist for every drilled position whose mover
// is not in check, never for one that is, and EVL_TPROBE pins its sign: after
// 1.e4 e5 2.Bc4 Nc6 3.Qh5 the flipped search must find Qxf7 mate +1.
{
  const before = fail;
  const replays = (from, sans) => {
    let q = from;
    for (const tok of sans) { const m = legal(q).find((x) => san(q, x) === tok); if (!m) return false; q = make(q, m); }
    return true;
  };
  let lines = 0, threats = 0;
  for (const [k, e] of Object.entries(EVL)) {
    const p = fenPos(k);
    for (const [lk, mk] of [["p", "m"], ["xp", "x"]]) {
      if (!e[mk]) { if (e[lk] !== undefined) bad(`EVL ${k}: ${lk} without ${mk}`); continue; }
      if (!Array.isArray(e[lk]) || e[lk].length !== e[mk].length) { bad(`EVL ${k}: ${lk} is not aligned with ${mk}`); continue; }
      e[lk].forEach((ln, i) => {
        if (!Array.isArray(ln) || ln[0] !== e[mk][i][1]) bad(`EVL ${k}: ${lk}[${i}] does not start with ${e[mk][i][1]}`);
        else if (!replays(p, ln)) bad(`EVL ${k}: ${lk}[${i}] does not replay`);
        else lines++;
      });
    }
    if (e.p && e.p[0].join(" ") !== e.pv.join(" ")) bad(`EVL ${k}: p[0] is not pv`);
    if (e.t === undefined) continue;
    if (inCheck(p)) { bad(`EVL ${k}: threat stored while the mover is in check`); continue; }
    const fp = { b: p.b, w: !p.w, cr: p.cr, ep: -1 };
    const [u, s, cp, mate, tpv] = e.t;
    const m = findMove(fp, u);
    if (!m) { bad(`EVL ${k}: threat ${u} is not legal with the move flipped`); continue; }
    if (san(fp, m) !== s) bad(`EVL ${k}: threat ${u} labelled ${s}, generator says ${san(fp, m)}`);
    if ((cp === null) === (mate === null) || mate === 0) bad(`EVL ${k}: threat needs exactly one of cp/mate`);
    if (!Array.isArray(tpv) || tpv[0] !== s || !replays(fp, tpv)) bad(`EVL ${k}: threat pv does not replay`);
    threats++;
  }
  // coverage: every drilled position whose mover is not in check has a threat row
  let drilled = 0;
  for (const l of LINES) {
    let q = l.start === START ? startPos() : fenPos(l.start.indexOf(" ") > 0 ? l.start : l.start + " w - -");
    l.moves.forEach(([u], i) => {
      if ((i % 2 === 0 ? "w" : "b") === l.you) {
        const k = keyOf(q), e = EVL[k];
        drilled++;
        if (e && !inCheck(q) && !e.t) bad(`${l.id}:${i}: drilled, not in check, and no threat row`);
      }
      q = make(q, findMove(q, u));
    });
  }
  const tp = EVL_TPROBE;
  if (!(tp && tp.pov === "threatener" && tp.uci === "h5f7" && tp.mate === 1 && tp.cp === null))
    bad(`EVL_TPROBE is ${JSON.stringify(tp)}: expected Qxf7 mate +1 for the threatening side`);
  else if (tp.fen !== keyOf([["e2e4"], ["e7e5"], ["f1c4"], ["b8c6"], ["d1h5"]].reduce((q, [u]) => make(q, findMove(q, u)), startPos())))
    bad("EVL_TPROBE is not the position after 1.e4 e5 2.Bc4 Nc6 3.Qh5");
  if (fail === before)
    console.log(`✓ ${lines} per-candidate lines replay; ${threats} threat rows legal with the move flipped, ` +
      `every drilled position covered (${drilled} drill plies), threat probe is mate +1 for the threatener`);
}

// 6b. the depth-28 rows (src/data/deep.js): same shape and rules as EVL minus
// the pv, every key already an EVL key and already in posKey form, deeper than
// the row it re-searches, and ranked best first. They are only ever read beside
// the EVL row, so a DEEP key with no EVL row would be a search nothing consults.
{
  let rows = 0, deepFail = fail;
  for (const [k, e] of Object.entries(DEEP)) {
    let p;
    try { p = fenPos(k); } catch { bad(`DEEP key does not parse: ${k}`); continue; }
    if (!EVL[k]) bad(`DEEP ${k}: no EVL row under the same key`);
    if (posKey(p) !== k) bad(`DEEP ${k}: not a posKey string (posKey gives ${posKey(p)})`);
    if (!(e.m && e.m.length)) { bad(`DEEP ${k}: no moves stored`); continue; }
    if (!(EVL[k] && e.d > EVL[k].d)) bad(`DEEP ${k}: depth ${e.d} is not deeper than the EVL row's`);
    if (e.x !== undefined) {
      if (!Array.isArray(e.x) || !e.x.length) { bad(`DEEP ${k}: x present but not a non-empty list`); continue; }
      const ranked = new Set(e.m.map((y) => y[0]));
      for (const y of e.x) if (ranked.has(y[0])) bad(`DEEP ${k}: ${y[0]} is in both m and x`);
    }
    for (let i = 1; i < e.m.length; i++)
      if (cmpScore(e.m[i - 1], e.m[i]) < 0) bad(`DEEP ${k}: ${e.m[i][1]} outranks ${e.m[i - 1][1]}; m must be best first`);
    for (const [uci, sanTxt, cp, mate] of [...e.m, ...(e.x || [])]) {
      const m = findMove(p, uci);
      if (!m) { bad(`DEEP ${k}: ${uci} is not legal`); continue; }
      if (san(p, m) !== sanTxt) bad(`DEEP ${k}: ${uci} labelled ${sanTxt}, generator says ${san(p, m)}`);
      if ((cp === null) === (mate === null)) bad(`DEEP ${k}: ${sanTxt} must have exactly one of cp/mate, has ${cp}/${mate}`);
      rows++;
    }
  }
  if (fail === deepFail)
    console.log(`✓ ${Object.keys(DEEP).length} depth-28 rows: keys parse and match EVL, ${rows} moves legal with matching SAN, ranked best first`);
}

// 6c. a note that calls its move the only move (or a one-move position) is a
// claim the depth-28 search can contradict. Where the board has a DEEP row and
// any other move there grades inside the accepting band (GRADE.accept), the
// note overstates and fails. "not the only move" is the honest form and passes.
{
  const ONLY = /\b(?<!not the )only (?:\w+ )?move\b|\b(?:one|single)[- ]move position\b/i;
  let claims = 0, checked = 0, onlyFail = fail;
  for (const l of LINES) {
    let q = l.start === START ? startPos() : fenPos(l.start.indexOf(" ") > 0 ? l.start : l.start + " w - -");
    l.moves.forEach(([u, , note], i) => {
      if (note && ONLY.test(note)) {
        claims++;
        const d = DEEP[keyOf(q)];
        if (d) {
          checked++;
          for (const y of [...d.m, ...(d.x || [])]) {
            if (y[0] === u) continue;
            const g = gradeRow(d, q, y[0]);
            if (GRADE.accept.includes(g.verdict))
              bad(`${l.id}:${i} note calls ${l.moves[i][1]} the only move, but depth ${d.d} accepts ${y[1]} (${g.verdict})`);
          }
        }
      }
      q = make(q, findMove(q, u));
    });
  }
  if (fail === onlyFail)
    console.log(`✓ ${claims} "only move" notes, ${checked} at depth-28 boards, none contradicted by another accepted move`);
}

// 7. fmtScore is the one formatting choke point for stored evals; a mate must
// never print as a pawn count. The function is written brace-free so it can be
// lifted out of app.js (which needs a DOM the sandbox above does not have).
{
  const src = js.match(/function fmtScore\(e\)\{[^}]*\}/);
  if (!src) bad("fmtScore not found in the bundle (or no longer regex-extractable)");
  else {
    const fmtScore = new Function("return " + src[0])();
    const eq = (got, want, label) => { if (got !== want) bad(`fmtScore ${label}: "${got}", expected "${want}"`); };
    eq(fmtScore({ cp: 34, mate: null }), "+0.3", "cp 34");
    eq(fmtScore({ cp: -120, mate: null }), "-1.2", "cp -120");
    eq(fmtScore({ cp: 0, mate: null }), "+0.0", "cp 0");
    for (const [e, label] of [[{ cp: null, mate: 3 }, "mate 3"], [{ cp: null, mate: -2 }, "mate -2"]]) {
      const s = fmtScore(e);
      if (!s.includes("mate")) bad(`fmtScore ${label}: "${s}" does not say mate`);
      if (/\d\.\d/.test(s)) bad(`fmtScore ${label}: "${s}" prints a mate with a decimal`);
    }
    eq(fmtScore({ cp: null, mate: 3 }), "mate in 3", "mate 3 wording");
    eq(fmtScore({ cp: null, mate: -2 }), "gets mated in 2", "mate -2 wording");
    console.log("✓ fmtScore: explicit sign on centipawns, mates never printed as pawn counts");
  }
}

// 8. no unimplemented references left in the bundle (catches a call left behind
// by a rename or a deleted function that a plain syntax check would miss)
const declared = new Set([...js.matchAll(/function\s+([A-Za-z_$][\w$]*)/g)].map((m) => m[1]));
[...js.matchAll(/(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=/g)].forEach((m) => declared.add(m[1]));
const builtin = new Set("if for while switch catch return typeof new function await async Number String Boolean parseInt parseFloat setTimeout setInterval clearTimeout clearInterval fetch requestAnimationFrame addEventListener removeEventListener console isNaN JSON Math Object Array Promise Date scrollTo rank url rgba translate var clamp break loses fails fianchetto".split(" "));
// strip string literals first (so a "//" inside a URL string can't be misread as a
// comment start), then strip comments: prose like "problem(s)" or "word (parenthetical)"
// in a comment is not a call.
const code = js.replace(/"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'|`(?:[^`\\]|\\.)*`/g, '""')
  .replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g, "");
const called = new Set([...code.matchAll(/(?<![\w.$])([a-z_$][\w$]*)\s*\(/g)].map((m) => m[1]));
const missing = [...called].filter((n) => !declared.has(n) && !builtin.has(n)).sort();
if (missing.length) bad(`calls with no definition: ${missing.join(", ")}`);
else console.log("✓ no undefined calls in the bundle");

// 9. no credential baked into the page. The masters panel authenticates with a
// lichess personal access token the user pastes at runtime; it lives in browser
// storage and must never reach the bundle. A token committed here would be
// published to GitHub Pages and readable by anyone who views source, so this is
// a shipping stop, not a warning. Matches lichess's own token prefixes.
const secrets = [...html.matchAll(/\b(?:lip|lio)_[A-Za-z0-9]{15,}/g)].map((m) => m[0]);
if (secrets.length) bad(`access token baked into the page: ${secrets.length} occurrence(s). Never commit a token; it belongs in browser storage only.`);
else console.log("✓ no access token in the bundle");

// 10. the page must not advertise a line or puzzle count it does not ship. The
// prose in src/html/ drifted to "47 lines" while LINES grew to 52, which is a
// promise to the user that the data no longer keeps.
const counts = [["line", LINES.length], ["puzzle", PZ.length]];
const WORDS = { 40: "Forty", 50: "Fifty", 60: "Sixty", 70: "Seventy", 80: "Eighty", 90: "Ninety" };
// attribute text counts too: the meta description carried the same stale number.
const text = html.replace(/<script>[\s\S]*<\/script>/, " ").replace(/<|>/g, " ");
for (const [what, n] of counts) {
  for (const m of text.matchAll(new RegExp(`([A-Za-z-]+|\\d+)\\s+${what}s\\b`, "gi"))) {
    const said = /^\d+$/.test(m[1]) ? +m[1]
      : Object.entries(WORDS).reduce((acc, [v, w]) =>
          m[1].toLowerCase().startsWith(w.toLowerCase())
            ? +v + ("one two three four five six seven eight nine".split(" ")
                .indexOf(m[1].toLowerCase().split("-")[1]) + 1) : acc, NaN);
    if (Number.isFinite(said) && said !== n) bad(`page says "${m[0]}" but ships ${n}`);
  }
}
if (!fail) console.log(`✓ page's stated counts match the data (${LINES.length} lines, ${PZ.length} puzzles)`);

// 10b. README.md makes the same promises in prose and drifted the same way
// ("829 moves across the 51 lines" long after LINES grew). Check the counts it
// states: lines, tactics puzzles, and the per-tag tallies in its provenance headings.
{
  const before = fail;
  const readme = readFileSync(join(root, "README.md"), "utf8");
  const tally = {};
  for (const l of LINES) tally[KIND[l.id]] = (tally[KIND[l.id]] || 0) + 1;
  for (const m of readme.matchAll(/\b(\d+) lines\b/g))
    if (+m[1] !== LINES.length) bad(`README says "${m[0]}" but ships ${LINES.length}`);
  for (const m of readme.matchAll(/\b(\d+) (?:tactics )?puzzles\b/g))
    if (+m[1] !== PZ.length) bad(`README says "${m[0]}" but ships ${PZ.length}`);
  let heads = 0;
  for (const m of readme.matchAll(/^### (`\w+`(?: and `\w+`)*) .*\(([\d +]+)\)\s*$/gm)) {
    const tags = [...m[1].matchAll(/`(\w+)`/g)].map((t) => t[1]);
    const said = m[2].split("+").map((x) => +x.trim());
    heads++;
    if (tags.length !== said.length) { bad(`README heading "${m[0]}" pairs ${tags.length} tags with ${said.length} counts`); continue; }
    tags.forEach((t, i) => { if ((tally[t] || 0) !== said[i]) bad(`README says ${said[i]} \`${t}\` lines, data has ${tally[t] || 0}`); });
  }
  if (heads < 5) bad(`README: expected the five provenance headings with counts, found ${heads}`);
  if (fail === before) console.log(`✓ README's stated counts match the data (${LINES.length} lines, ${PZ.length} puzzles, ${heads} tag headings)`);
}

// 11. W5-B release checks on the analysis itself.
// (a) Depth is part of the reproducibility contract: one depth for the whole
//     table, or two rows are not comparable and lossCp is meaningless.
// (b) The sign convention, checked across the table rather than only at the one
//     probe position: a parent's best score and its child's should NEGATE, since
//     both are side-to-move relative. If a regeneration ever flipped them
//     White-relative these would match unsigned instead.
// (c) Every move the trainer asks the user to play must have a score. It is
//     allowed to be unanalysed - that is a first-class neutral outcome - but the
//     repertoire's own moves are the ones build-evals searches individually, so
//     an unanalysed one means that pass did not run.
{
  const depths = new Set(Object.values(EVL).map((r) => r.d));
  if (depths.size !== 1) bad(`EVL mixes search depths: ${[...depths].join(", ")}`);

  let negating = 0, matching = 0;
  for (const [k, r] of Object.entries(EVL)) {
    if (r.m[0][2] === null) continue;
    let p; try { p = fenPos(k); } catch { continue; }
    const m = findMove(p, r.m[0][0]);
    if (!m) continue;
    const child = EVL[keyOf(make(p, m))];
    if (!child || child.m[0][2] === null) continue;
    if (Math.abs(r.m[0][2] + child.m[0][2]) <= 40) negating++;
    else if (Math.abs(r.m[0][2] - child.m[0][2]) <= 40) matching++;
  }
  if (negating && negating <= matching)
    bad(`parent/child scores match unsigned ${matching} times against ${negating} negating: the sign convention looks White-relative`);

  let unscored = 0;
  for (const l of LINES) {
    let p = l.start === START ? startPos() : fenPos(l.start);
    l.moves.forEach((mv, i) => {
      const m = findMove(p, mv[0]);
      if (!m) return;
      if ((i % 2 === 0 ? "w" : "b") === l.you &&
          gradeMove(EVL[keyOf(p)], p, m).verdict === "unknown") unscored++;
      p = make(p, m);
    });
  }
  if (unscored) bad(`${unscored} drilled repertoire moves have no score; run tools/build-evals.mjs`);
  if (!fail) console.log(`\u2713 analysis: one depth (${[...depths][0]}), ${negating} parent/child pairs negate, every drilled move scored`);
}

// 12. The annotation-mark policy, enforced rather than trusted. CLAUDE.md:
// "Do not add a new mark to a move unless the line's own source uses it." A
// `model` or `synthetic` line was written for this trainer, so no source exists
// that could have written one - a mark there is this repo's own verdict wearing
// a citation's clothes. The W4 audit removed five on exactly that ground.
{
  const marked = [];
  for (const l of LINES) l.moves.forEach((m, i) => { if (/[!?]/.test(m[1])) marked.push([l.id, i, m[1], KIND[l.id]]); });
  const unsourceable = marked.filter(([, , , k]) => k === "model" || k === "synthetic");
  if (unsourceable.length)
    bad(`annotation marks on lines with no possible source: ${unsourceable.map(([id, i, sanTxt, k]) => `${id}:${i} ${sanTxt} (${k})`).join(", ")}`);
  else console.log(`\u2713 ${marked.length} annotation marks, none on a model or synthetic line`);
}

// 13. Counted player choices (src/data/choices.js, tools/count-choices.mjs). The
// app names a "common mistake" from this table and prices it from EVL, so every
// row must be a drilled position, every move legal with the engine's SAN and
// already scored, every count a real count no larger than its parent, and every
// shipped move over the documented floor in at least one band. The bands are
// read by index against FRQ_BANDS, so the two lists must be the same list.
{
  const before = fail;
  if (JSON.stringify(CHO_BANDS) !== JSON.stringify(FRQ_BANDS))
    bad(`CHO_BANDS ${JSON.stringify(CHO_BANDS)} is not FRQ_BANDS ${JSON.stringify(FRQ_BANDS)}`);
  let nPos = 0, nMoves = 0, mistakes = 0, unscored = 0;
  for (const [key, [parent, ...mv]] of Object.entries(CHO)) {
    nPos++;
    const row = EVL[key];
    if (!row) { bad(`CHO row ${key} is not a drilled position`); continue; }
    if (!Array.isArray(parent) || parent.length !== FRQ_BANDS.length || !parent.every((n) => Number.isInteger(n) && n >= 0))
      bad(`CHO ${key}: bad parent counts ${JSON.stringify(parent)}`);
    const pos = fenPos(key);
    const scored = new Set([...row.m, ...(row.x || [])].map((e) => e[0]));
    for (const [uci, s, ...g] of mv) {
      nMoves++;
      const m = findMove(pos, uci);
      if (!m) { bad(`CHO ${key}: ${uci} is not legal`); continue; }
      if (san(pos, m) !== s) bad(`CHO ${key}: ${uci} labelled ${s}, engine says ${san(pos, m)}`);
      // Every shipped choice is priced: where a shared forced search is fixed,
      // count-choices marks the choice "alone" and it gets a search of its own.
      if (!scored.has(uci)) { unscored++; bad(`CHO ${key}: ${s} has no score in EVL; rerun count-choices --tsv and build-evals --force`); }
      if (g.length !== parent.length || g.some((x, b) => !Number.isInteger(x) || x < 0 || x > parent[b]))
        bad(`CHO ${key}: ${s} counts ${JSON.stringify(g)} do not fit parent ${JSON.stringify(parent)}`);
      if (!g.some((x, b) => parent[b] >= CHO_FLOOR.parent && x >= CHO_FLOOR.games && x / parent[b] >= CHO_FLOOR.share))
        bad(`CHO ${key}: ${s} is under the floor in every band`);
      if (["concession", "inferior", "losing"].includes(gradeMove(row, pos, uci).verdict)) mistakes++;
    }
  }
  if (!nPos) bad("CHO is empty: run tools/count-choices.mjs --emit");
  if (fail === before) console.log(`\u2713 counted choices: ${nPos} positions, ${nMoves} moves, all legal and scored; ${mistakes} priced as a concession or worse`);
}

// TICKETS.md holds open work only: a shipped ticket is deleted, never ticked or
// moved to a done section (CLAUDE.md, "Tickets and features"). Enforced here so
// the rule does not depend on memory.
{
  const before = fail;
  let t = "";
  try { t = readFileSync(join(root, "TICKETS.md"), "utf8"); } catch { bad("TICKETS.md is missing"); }
  if (/\u2705|\[x\]/i.test(t)) bad("TICKETS.md has a tick mark: delete a shipped ticket instead");
  if (/^#+\s*(done|shipped|closed)\b/im.test(t)) bad("TICKETS.md has a done section: delete shipped tickets instead");
  if (fail === before) console.log("\u2713 TICKETS.md holds open work only");
}

if (fail) { console.error(`\n${fail} problem(s). Do not ship.`); process.exit(1); }
console.log("\nAll checks passed.");
