#!/usr/bin/env node
// Data + engine verification. Runs against docs/ (build first).
// Exits non-zero on any problem, so it works as a pre-commit / CI gate.
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "docs/index.html"), "utf8");
const js = html.slice(html.indexOf("<script>") + 8, html.lastIndexOf("</script>"));

// Evaluate the shipped bundle in a bare sandbox: no DOM, so stop before app.js.
const upto = js.indexOf("/* ================= state ================= */");
const bundle = js.slice(0, upto);
const ctx = {};
new Function("ctx", bundle + "\nObject.assign(ctx,{LINES,KIND,SRC,PZ,ECO,START,startPos,fenPos,findMove,make,san,perft,legal,uciOf,sq,ix});")(ctx);
const { LINES, KIND, SRC, PZ, ECO, START, startPos, fenPos, findMove, make, san, perft } = ctx;

let fail = 0;
const bad = (m) => { console.error("  ✗ " + m); fail++; };

// 1. move generator against the standard perft positions
const PERFT = [
  ["start", null, [20, 400, 8902, 197281]],
  ["kiwipete", "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq -", [48, 2039, 97862]],
  ["position 3", "8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - -", [14, 191, 2812, 43238]],
  ["position 4", "r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq -", [6, 264, 9467]],
];
for (const [name, fen, expected] of PERFT) {
  const p = fen ? fenPos(fen) : startPos();
  expected.forEach((want, i) => {
    const got = perft(p, i + 1);
    if (got !== want) bad(`perft ${name} depth ${i + 1}: ${got}, expected ${want}`);
  });
}
console.log(`✓ move generator matches perft on ${PERFT.length} positions`);

// 2. every line replays legally and its notation is what the generator produces
const TAGS = new Set(["game", "book", "eco", "theory", "model", "synthetic"]);
const ids = new Set(LINES.map((l) => l.id));
for (const k of Object.keys(KIND)) if (!ids.has(k)) bad(`KIND tags unknown line "${k}"`);
for (const k of Object.keys(SRC)) if (!ids.has(k)) bad(`SRC has a source for unknown line "${k}"`);
let moves = 0;
const kinds = {};
for (const l of LINES) {
  const tag = KIND[l.id];
  kinds[tag || "untagged"] = (kinds[tag || "untagged"] || 0) + 1;
  if (!tag) bad(`${l.id} has no provenance tag`);
  else if (!TAGS.has(tag)) bad(`${l.id} has an unrecognised tag "${tag}"`);
  if (tag === "game" && !SRC[l.id]) bad(`${l.id} is tagged game but has no entry in SRC`);
  let p = l.start === START ? startPos() : fenPos(l.start);
  const seenNotes = new Map();
  l.moves.forEach((mv, i) => {
    const m = findMove(p, mv[0]);
    if (!m) return bad(`${l.id} move ${i + 1} (${mv[1]}) is not legal`);
    const produced = san(p, m).replace(/[+#]/g, "");
    if (produced !== mv[1].replace(/[+#!?]/g, ""))
      bad(`${l.id} move ${i + 1} is labelled ${mv[1]}, generator says ${produced}`);
    if (mv[2]) {
      if (seenNotes.has(mv[2]))
        bad(`${l.id}: the note "${mv[2]}" is on both ply ${seenNotes.get(mv[2])} and ply ${i + 1}`);
      else seenNotes.set(mv[2], i + 1);
    }
    moves++;
    p = make(p, m);
  });
}
console.log(`✓ ${LINES.length} lines, ${moves} moves, all legal with matching notation`);
console.log(`  tags: ${Object.entries(kinds).map(([k, v]) => `${k} ${v}`).join(", ")}`);

// 3. ECO stays in sync with the lines it names (eco.js is generated by
// tools/build-eco.mjs from the same LINES data, so it can drift if lines.js
// changes without a rebuild)
const lineLen = new Map(LINES.map((l) => [l.id, l.moves.length]));
for (const [id, entries] of Object.entries(ECO)) {
  if (!lineLen.has(id)) { bad(`ECO has entries for unknown line "${id}"`); continue; }
  for (const [ply] of entries)
    if (ply > lineLen.get(id)) bad(`ECO ${id}: ply ${ply} is beyond its ${lineLen.get(id)} moves`);
}
console.log(`✓ ${Object.keys(ECO).length} ECO entries reference real lines and in-range plies`);

// 4. every puzzle replays from its FEN with matching display SAN
let pz = 0;
for (const z of PZ) {
  let p;
  try { p = fenPos(z.f); } catch { bad(`puzzle ${z.id}: unreadable FEN`); continue; }
  let ok = true;
  for (let i = 0; i < z.m.length; i++) {
    const m = findMove(p, z.m[i]);
    if (!m) { bad(`puzzle ${z.id}: ${z.m[i]} is not legal`); ok = false; break; }
    const produced = san(p, m).replace(/[+#]/g, "");
    const stored = (z.s[i] || "").replace(/[+#!?]/g, "");
    if (produced !== stored) { bad(`puzzle ${z.id} move ${i + 1} is labelled ${z.s[i]}, generator says ${produced}`); ok = false; }
    p = make(p, m);
  }
  if (ok) pz++;
}
console.log(`✓ ${pz}/${PZ.length} puzzles replay legally with matching display notation`);

// 5. no unimplemented references left in the bundle (catches a call left behind
// by a rename or a deleted function that a plain syntax check would miss)
const declared = new Set([...js.matchAll(/function\s+([A-Za-z_$][\w$]*)/g)].map((m) => m[1]));
[...js.matchAll(/(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=/g)].forEach((m) => declared.add(m[1]));
const builtin = new Set("if for while switch catch return typeof new function await async Number String Boolean parseInt parseFloat setTimeout setInterval clearTimeout clearInterval fetch requestAnimationFrame addEventListener removeEventListener console isNaN JSON Math Object Array Promise Date scrollTo rank url rgba translate var clamp break loses fails fianchetto".split(" "));
// strip string literals first (so a "//" inside a URL string can't be misread as a
// comment start), then strip comments: prose like "problem(s)" or "word (parenthetical)"
// in a comment is not a call.
const code = js.replace(/"(?:[^"\\\n]|\\.)*"|'(?:[^'\\\n]|\\.)*'|`(?:[^`\\]|\\.)*`/g, '""')
  .replace(/\/\/[^\n]*|\/\*[\s\S]*?\*\//g, "");
const called = new Set([...code.matchAll(/(?<![\w.$])([a-z_$][\w$]*)\s*\(/g)].map((m) => m[1]));
const missing = [...called].filter((n) => !declared.has(n) && !builtin.has(n)).sort();
if (missing.length) bad(`calls with no definition: ${missing.join(", ")}`);
else console.log("✓ no undefined calls in the bundle");

if (fail) { console.error(`\n${fail} problem(s). Do not ship.`); process.exit(1); }
console.log("\nAll checks passed.");
