#!/usr/bin/env node
// Regenerates the embedded @font-face block in src/styles.css: subsets the two
// self-hosted families (Zilla Slab 600/700 for headings, IBM Plex Mono 400/600
// for notation and stats) to the glyphs the app can actually display, compresses
// to WOFF2 and inlines them as base64 so the built page stays a single file with
// no external requests. Requires data-src/fonts/*.ttf (tools/fetch-assets.sh)
// and pyftsubset with brotli (pip install fonttools brotli).
//
// The glyph set below is a contract: every non-ASCII character that any
// user-facing string in src/ can produce must be listed, or it ships as a
// fallback-font glyph. If you add prose with a new character, add it here and
// rerun. Symbols the fonts simply lack (arrows, ⏸, ▶) are requested anyway and
// reported; those fall through to the system font, same as before self-hosting.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "data-src/fonts");
const cssFile = join(root, "src/styles.css");

// U+0020-007E  printable ASCII (all letters, digits, notation)
// U+00A0       no-break space
// U+00C0-00FF  Latin-1 letters — covers the ä/ü in player and opening names now,
//              and the é/ö/ñ a regenerated eco.js could plausibly introduce
// U+00B7       middle dot separator      U+2013/2014  en/em dash
// U+2018/2019/201C/201D  curly quotes    U+2026       ellipsis
// U+2190/2192  arrows                    U+22EE       vertical ellipsis (menu)
// U+23F8       pause                     U+25B6/25C0  play/back triangles
// U+2713       tick
const UNICODES =
  "U+0020-007E,U+00A0,U+00B7,U+00C0-00FF,U+2013,U+2014,U+2018,U+2019," +
  "U+201C,U+201D,U+2026,U+2190,U+2192,U+22EE,U+23F8,U+25B6,U+25C0,U+2713";

const FACES = [
  { file: "zillaslab-ZillaSlab-SemiBold.ttf", family: "Zilla Slab", weight: 600 },
  { file: "zillaslab-ZillaSlab-Bold.ttf", family: "Zilla Slab", weight: 700 },
  { file: "ibmplexmono-IBMPlexMono-Regular.ttf", family: "IBM Plex Mono", weight: 400 },
  { file: "ibmplexmono-IBMPlexMono-SemiBold.ttf", family: "IBM Plex Mono", weight: 600 },
];

for (const f of FACES) {
  if (!existsSync(join(src, f.file))) {
    throw new Error(`missing ${f.file} - run tools/fetch-assets.sh first`);
  }
}

const faces = [];
let total = 0;
for (const f of FACES) {
  const out = join(src, f.file.replace(/\.ttf$/, ".subset.woff2"));
  execFileSync("pyftsubset", [
    join(src, f.file),
    `--unicodes=${UNICODES}`,
    "--flavor=woff2",
    "--no-hinting",
    "--desubroutinize",
    `--output-file=${out}`,
  ]);
  const buf = readFileSync(out);
  total += buf.length;
  console.log(`${f.family} ${f.weight}: ${(buf.length / 1024).toFixed(1)} KB woff2`);
  faces.push(
    `  @font-face{font-family:"${f.family}";font-style:normal;font-weight:${f.weight};` +
      `font-display:swap;src:url(data:font/woff2;base64,${buf.toString("base64")}) format("woff2")}`,
  );
}
console.log(`total ${(total / 1024).toFixed(1)} KB before base64`);

const block = [
  "  /* Embedded fonts - generated by tools/build-fonts.mjs, do not edit by hand.",
  "     Zilla Slab (c) Typotheque (typotheque.com), designed by Peter Bilak, Nikola Djurek;",
  "     IBM Plex Mono (c) IBM Corp. (github.com/IBM/plex), designed by Mike Abbink and Bold Monday.",
  "     Both are licensed under the SIL Open Font License 1.1 (openfontlicense.org),",
  "     which permits this embedding. Subset to the glyphs the app displays. */",
  ...faces,
].join("\n");

const css = readFileSync(cssFile, "utf8");
const re = /(\/\*__FONTS__\*\/)[\s\S]*?(\/\*__END_FONTS__\*\/)/;
if (!re.test(css)) throw new Error("styles.css is missing the /*__FONTS__*/ markers");
writeFileSync(cssFile, css.replace(re, `$1\n${block}\n  $2`));
console.log("wrote @font-face block into src/styles.css - now run npm run build");
