#!/usr/bin/env node
// Joins the counted frequencies against what LINES actually answers, and
// writes research/COVERAGE-MATRIX.md. Coverage is decided by position
// identity, so a reply answered in a transposed line counts as covered.
//
//   node tools/coverage-matrix.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "docs/index.html"), "utf8");
const js = html.slice(html.indexOf("<script>") + 8, html.lastIndexOf("</script>"));
const ctx = {};
new Function("ctx", js.slice(0, js.indexOf("/* ================= state ================= */")) +
  "\nObject.assign(ctx,{LINES,KIND,startPos,fenPos,make,san,legal,uciOf,fenOf,EVL});")(ctx);
const { LINES, KIND, startPos, fenPos, make, san, legal, uciOf, fenOf, EVL } = ctx;
const keyFen = (p) => p.ep < 0 || legal(p).some((m) => m.ep)
  ? fenOf(p) : fenOf({ b: p.b, w: p.w, cr: p.cr, ep: -1 });

// Every (position, move) the repertoire contains, split by which side the line
// trains. A Colle reply answered only inside a Hippopotamus line gives the White
// repertoire nothing, so the two halves must not credit each other.
const SEEN = { w: new Map(), b: new Map() };
for (const l of LINES) {
  const into = SEEN[l.you];
  let p = startPos();
  for (const [uci] of l.moves) {
    const k = keyFen(p);
    if (!into.has(k)) into.set(k, new Map());
    const at = into.get(k);
    if (!at.has(uci)) at.set(uci, new Set());
    at.get(uci).add(l.id);
    p = make(p, legal(p).find((x) => uciOf(x) === uci));
  }
  // Index the line's terminal position too. Without this a reply that leads
  // exactly into where a line stops reads "missing" when the repertoire does
  // reach it; eco-averb's final position was the case that exposed it.
  const end = keyFen(p);
  if (!into.has(end)) into.set(end, new Map());
}

const load = (f) => existsSync(join(root, f)) ? JSON.parse(readFileSync(join(root, f), "utf8")) : null;
const SIDES = [
  { side: "w", title: "Colle as White — what Black replies",
    player: load("research/freq-colle-player.json"),
    masters: [["pgnmentor", load("research/freq-colle-master-pgnmentor.json")],
              ["twic", load("research/freq-colle-master-twic.json")]] },
  { side: "b", title: "Hippopotamus as Black — what White plays",
    player: load("research/freq-hippo-player.json"),
    masters: [["pgnmentor", load("research/freq-hippo-master-pgnmentor.json")],
              ["twic", load("research/freq-hippo-master-twic.json")]] },
];

const MIN_SHARE = 0.02;               // below this a reply is listed only if a line covers it
const out = [];
out.push("# Coverage matrix", "",
  "Generated by `tools/coverage-matrix.mjs` from the counted frequencies in",
  "`research/freq-*.json`. Read [METHOD.md](METHOD.md) first: the master",
  "collections are selected by opening classification, so their shares are",
  "conditional on that classification and are **not** comparable with the",
  "player pool's. Frequency is not quality; nothing here says a common move is",
  "good or a rare one is bad.", "",
  "`covered` — a line **that trains this side** plays this reply from this exact",
  "position identity. A Colle reply answered only inside a Hippopotamus line is",
  "not coverage for the White repertoire, and is not counted as such here.",
  "`transposes` — no line plays it here, but some line does reach the position",
  "it leads to by another move order, so the repertoire has an answer even",
  "though nothing drills this order. `missing` — neither.", "",
  "`transposes` only catches an *immediate* rejoin. Many `missing` replies will",
  "also rejoin the repertoire after one or two system moves (1.d4 d5 2.Nf3 e6",
  "is answered 3.e3 like everything else); this matrix does not chase those, so",
  "`missing` reads as \"no line contains this move order\", not \"no answer",
  "exists\".", "",
  "`eval` — the position after the reply has a stored Stockfish row in `EVL`.", "");

let totals = { covered: 0, transposes: 0, missing: 0 };
for (const s of SIDES) {
  out.push(`## ${s.title}`, "");
  if (!s.player) { out.push("_No player-pool data counted yet._", ""); continue; }
  out.push(`Player pool: ${s.player.games_read.toLocaleString()} games read, ` +
    `${s.player.games_in_tree.toLocaleString()} entered the tree, ` +
    `${s.player.positions.length} positions at or above the minimum sample. ` +
    `Filters: ${JSON.stringify(s.player.filters)}. Retrieved ${s.player.retrieved}.`, "");
  const mIdx = s.masters.map(([name, doc]) =>
    [name, doc ? new Map(doc.positions.map((p) => [p.key, p])) : null]);
  for (const pos of s.player.positions) {
    const at = SEEN[s.side].get(pos.key) || new Map();
    const rows = pos.replies.filter((r) => r.share >= MIN_SHARE || at.has(r.uci));
    if (!rows.length) continue;
    out.push(`### ${pos.fen}`, "",
      `${pos.parent_games.toLocaleString()} games reached this position (player pool).`, "",
      "| reply | player share | " + mIdx.map(([n]) => n + " share").join(" | ") +
      " | coverage | answered in | eval |", "|---|---|" + mIdx.map(() => "---|").join("") + "---|---|---|");
    for (const r of rows) {
      const lines = at.get(r.uci);
      const ms = mIdx.map(([, idx]) => {
        if (!idx) return "—";
        const mp = idx.get(pos.key);
        if (!mp) return "—";
        const mr = mp.replies.find((x) => x.uci === r.uci);
        return mr ? `${(mr.share * 100).toFixed(1)}% (${mr.games})` : `0 / ${mp.parent_games}`;
      });
      // does the position this reply leads to carry a stored evaluation, and
      // does any line reach it by some other move order?
      const base = fenPos(pos.fen);
      const mv = legal(base).find((x) => uciOf(x) === r.uci);
      const afterKey = mv ? keyFen(make(base, mv)) : null;
      const after = afterKey && EVL && EVL[afterKey] ? "yes" : "no";
      const cov = lines ? "covered" : (afterKey && SEEN[s.side].has(afterKey) ? "transposes" : "missing");
      totals[cov] = (totals[cov] || 0) + 1;
      out.push(`| ${r.san} | ${(r.share * 100).toFixed(1)}% (${r.games}) | ${ms.join(" | ")} | ` +
        `${cov} | ${lines ? [...lines].map((x) => `\`${x}\` (${KIND[x]})`).join(", ") : "—"} | ${after} |`);
    }
    out.push("");
  }
}
out.push("## Totals", "",
  `${totals.covered} counted replies are played somewhere in \`LINES\` from the ` +
  `same position, ${totals.transposes} lead to a position a line reaches by ` +
  `another order, and ${totals.missing} are neither. A "missing" row is a ` +
  "candidate for coverage, " +
  "not an obligation: the plan stops at a teachable decision rather than " +
  "expanding an unlimited game tree.", "");
writeFileSync(join(root, "research/COVERAGE-MATRIX.md"), out.join("\n"));
console.log(`covered ${totals.covered}, transposes ${totals.transposes}, missing ${totals.missing} -> research/COVERAGE-MATRIX.md`);
